---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodepool-builder
  namespace: zuul
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zuul-executor
  namespace: zuul
---
kind: SecurityContextConstraints
apiVersion: v1
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedFlexVolumes: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
# groups:
# - system:cluster-admins
# - system:nodes
# - system:masters
metadata:
  annotations:
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  name: zuul-scc
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
  uid: 1001
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
# supplementalGroups:
#   type: RunAsAny
users:
  - system:serviceaccount:zuul:zuul-executor
  - system:serviceaccount:zuul:nodepool-builder
# - system:admin
# - system:serviceaccount:openshift-infra:build-controller
# - system:serviceaccount:default:pvinstaller
# - system:serviceaccount:default:registry
# - system:serviceaccount:default:router
groups:
  - zuul
# volumes:
# - '*'
---
